apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fkp0xzn37-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fkp0xzn37-java-quarkus-gitops